name: Linux-build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  BUILD_TYPE: Release
  BUILD_PARALLEL: 4

jobs:
  linux:
    strategy:
      fail-fast: false
    name: ubuntu-test
    
    # work around until pumi is updated
    #runs-on: ubuntu-18.04
    runs-on: ubuntu-latest

    steps:

    - name: install mpich and gcc
      run: |
           sudo apt update
           sudo apt install gcc-10 g++-10 mpich

    - name: Checkout SCOREC core
      uses: actions/checkout@v2
      with:
        repository: SCOREC/core
        path: pumi
        submodules: recursive

    - name: Core Configure CMake
      env:
        MPICH_CC: gcc-10
        MPICH_CXX: g++-10
      run: cmake -S ${{github.workspace}}/pumi -B ${{github.workspace}}/pumi/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_C_COMPILER=mpicc -DCMAKE_VERBOSE_MAKEFILE=ON -DIS_TESTING=OFF
#-DMESHES=${{github.workspace}}/pumi/pumi-meshes

    - name: Build PUMI
      env:
        MPICH_CC: gcc-10
        MPICH_CXX: g++-10
      run: cmake --build ${{github.workspace}}/pumi/build --config ${{env.BUILD_TYPE}} -j ${{env.BUILD_PARALLEL}}

    - name: Install PUMI
      run: cmake --install ${{github.workspace}}/pumi/build --config ${{env.BUILD_TYPE}}  --prefix ${{github.workspace}}/install/pumi

    #- name: Test PUMI
    #  working-directory: ${{github.workspace}}/mumfim/build
    #  run: ctest  -C ${{env.BUILD_TYPE}} --output-on-failure

    - name: Checkout MuMFiM
      uses: actions/checkout@v2
      with:
        repository: SCOREC/mumfim
        path: mumfim

    - name: MuMFiM Configure CMake
      env:
        MPICH_CC: gcc-10
        MPICH_CXX: g++-10
      run: cmake -S ${{github.workspace}}/mumfim  -B ${{github.workspace}}/mumfim/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_VERBOSE_MAKEFILE=ON -DSCOREC_DIR=${{github.workspace}}/install/pumi/lib/cmake/SCOREC

    - name: Build MuMFiM
      env:
        MPICH_CC: gcc-10
        MPICH_CXX: g++-10
      run: cmake --build ${{github.workspace}}/mumfim/build --config ${{env.BUILD_TYPE}} -j ${{env.BUILD_PARALLEL}}

    - name: Test MuMFiM
      working-directory: ${{github.workspace}}/mumfim/build
      run: ctest  -C ${{env.BUILD_TYPE}} --output-on-failure
      
