name: test

on: [push, pull_request]

env:
  BUILD_TYPE: Release
  BUILD_PARALLEL: 4

jobs:
  linux:
    strategy:
      fail-fast: false
    name: ubuntu-test
    
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3

    - name : spack
      run: |
        git clone -c feature.manyFiles=true https://github.com/spack/spack.git
        . spack/share/spack/setup-env.sh
        spack mirror add binary_mirror  https://binaries.spack.io/releases/v0.18
        spack buildcache keys --install --trust

        spack env create mumfim
        spack env activate mumfim

        cd ~
        git clone https://github.com/jacobmerson/mumfim-spack.git
        spack repo add ~/mumfim-spack/mumfim

        spack add mumfim@develop%gcc@7.5.0 +tests
        spack develop --no-clone --path ${{github.workspace}} mumfim@develop 
        
        spack install 

        cd `spack location -b mumfim`
        ctest --output-on-failure

      

    
