name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release
  BUILD_PARALLEL: 4

jobs:
  linux:
    strategy:
      fail-fast: false
    name: ubuntu-test
    
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      #run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 
      run: git clone -c feature.manyFiles=true https://github.com/spack/spack.git
      run: . spack/share/spack/setup-env.sh
      run: time spack spec zlib
      run: spack find -b

    - name: Build
      #run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j ${{env.BUILD_PARALLEL}}

    - name: Test
      #working-directory: ${{github.workspace}}/build
      #run: ctest  -C ${{env.BUILD_TYPE}} --output-on-failure
      
