name: test

on: [push, pull_request]

env:
  BUILD_TYPE: Release
  BUILD_PARALLEL: 4

jobs:
  linux:
    strategy:
      fail-fast: false
    name: ubuntu-test
    
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3

    - run: |
        git clone -c feature.manyFiles=true https://github.com/spack/spack.git
        . spack/share/spack/setup-env.sh
        time spack spec zlib
        spack find -b
        spack mirror add binary_mirror  https://binaries.spack.io/releases/v0.18
        spack buildcache keys --install --trust
        spack install zlib

    
